org: solarnius
app: classify-serverless
service: classify-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

	
plugins:
  - serverless-api-gateway-throttling
 
custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 1
    maxConcurrentRequests: 100

functions:
  classify:
    handler: classify.handler
    timeout: 30
    events:
      - httpApi:
          path: /
          method: get
